# Generated by Django 5.2.5 on 2025-08-12 12:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionsource',
            name='source_type',
            field=models.CharField(choices=[('image', 'Image Upload'), ('multi_image', 'Multi-Image Upload'), ('url', 'Web URL'), ('text', 'Manual Text Input'), ('api', 'API Import')], max_length=20),
        ),
        migrations.CreateModel(
            name='MultiImageSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.FileField(upload_to='recipe_sources/multi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'heif'])])),
                ('page_number', models.PositiveIntegerField(default=1, help_text='Page number in the recipe')),
                ('page_type', models.CharField(choices=[('ingredients', 'Ingredients Page'), ('instructions', 'Instructions Page'), ('metadata', 'Metadata Page'), ('unknown', 'Unknown')], default='unknown', help_text='Type of content on this page', max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from this image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_images', to='recipe_ingestion.ingestionsource')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
