# Generated by Django 5.2.5 on 2025-09-20 20:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairedPhotoSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pairing_token', models.CharField(help_text='Token to link ingredients and directions photos', max_length=100, unique=True)),
                ('recipe_name', models.CharField(blank=True, help_text='Recipe name if provided', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ingredients_uploaded', 'Ingredients Uploaded'), ('directions_uploaded', 'Directions Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ingredients_photo', models.FileField(blank=True, null=True, upload_to='recipe_sources/paired/ingredients/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'heif'])])),
                ('directions_photo', models.FileField(blank=True, null=True, upload_to='recipe_sources/paired/directions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'heif'])])),
                ('ingredients_text', models.TextField(blank=True, help_text='Extracted text from ingredients photo')),
                ('directions_text', models.TextField(blank=True, help_text='Extracted text from directions photo')),
                ('combined_text', models.TextField(blank=True, help_text='Combined text from both photos')),
                ('is_test', models.BooleanField(default=False, help_text='Mark as test data for easy filtering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paired_photo_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paired Photo Source',
                'verbose_name_plural': 'Paired Photo Sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PairedPhotoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('recipes_found', models.PositiveIntegerField(default=0)),
                ('recipes_processed', models.PositiveIntegerField(default=0)),
                ('paired_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recipe_ingestion.pairedphotosource')),
            ],
        ),
    ]
