# Generated by Django 5.2.5 on 2025-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingestion', '0002_alter_ingestionsource_source_type_multiimagesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionsource',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Mark as test data for easy filtering'),
        ),
    ]
