# Generated by Django 5.2.5 on 2025-08-30 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingestion', '0003_ingestionsource_is_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionsource',
            name='source_type',
            field=models.CharField(choices=[('image', 'Image Upload'), ('multi_image', 'Multi-Image Upload'), ('url', 'Web URL'), ('text', 'Manual Text Input'), ('api', 'API Import'), ('email', 'Email Attachment')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmailIngestionSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('sender_name', models.CharField(blank=True, help_text='Name of the sender', max_length=200)),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('received_at', models.DateTimeField(help_text='When the email was received')),
                ('message_id', models.CharField(help_text='Email message ID for deduplication', max_length=500, unique=True)),
                ('raw_email_content', models.TextField(blank=True, help_text='Raw email content for debugging')),
                ('attachment_count', models.PositiveIntegerField(default=0, help_text='Number of attachments processed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_details', to='recipe_ingestion.ingestionsource')),
            ],
            options={
                'verbose_name': 'Email Ingestion Source',
                'verbose_name_plural': 'Email Ingestion Sources',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Original filename of the attachment', max_length=500)),
                ('content_type', models.CharField(help_text='MIME type of the attachment', max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='Size of the attachment in bytes')),
                ('attachment_file', models.FileField(help_text='Saved attachment file', upload_to='recipe_sources/email/')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this attachment has been processed')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='recipe_ingestion.emailingestionsource')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEmailMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Email address that can send recipes', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this email mapping is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Email Mapping',
                'verbose_name_plural': 'User Email Mappings',
            },
        ),
    ]
