# Generated by Django 5.2.5 on 2025-08-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingestion', '0004_alter_ingestionsource_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedEmailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Email address that can send recipes', max_length=254, unique=True)),
                ('sender_name', models.CharField(blank=True, help_text='Optional name for the sender', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sender is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approved Email Sender',
                'verbose_name_plural': 'Approved Email Senders',
                'ordering': ['email_address'],
            },
        ),
        migrations.AddField(
            model_name='emailingestionsource',
            name='is_approved_sender',
            field=models.BooleanField(default=False, help_text='Whether sender was on approved list'),
        ),
        migrations.DeleteModel(
            name='UserEmailMapping',
        ),
    ]
