# Generated by Django 5.2.5 on 2025-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingestion', '0005_approvedemailsender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='attachment_type',
            field=models.CharField(choices=[('attachment', 'Attachment'), ('embedded', 'Embedded Image')], default='attachment', help_text='Type of attachment - traditional attachment or embedded image', max_length=20),
        ),
    ]
