# Generated by Django 5.2.5 on 2025-08-12 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenary_pantry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_name',
            field=models.CharField(blank=True, help_text="Source of the recipe (e.g., 'Better Homes and Gardens Cookbook')", max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_type',
            field=models.CharField(blank=True, help_text="Type of source (e.g., 'cookbook', 'website', 'magazine')", max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL where recipe was found', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name', 'source_name', 'created_by')},
        ),
    ]
